### create user
POST {{host}}/register-user
Content-Type: application/json

{
  "userName": "Sample Name 3",
  "description": "test",
  "hobby": ["study", "coding"],
  "latitude": 87.3243,
  "hardness": 120.2321
}

### find around friends
GET {{host}}/around-users?user=Sample Name&range=100000000&limit=5

###  upload user image
POST {{host}}/upload-image
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="userName"
Content-Type: text/plain

UserName
--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="test-image.webp"
Content-Type: image/webp

< ./temp/test-image.webp
--WebAppBoundary--