[db]
database = "mysql"
url = "metting:metting@tcp(localhost:3306)/metting"

[aws]
key = ""
secretKey = ""
region = "ap-northeast-2"
bucket = "geo-query-aws-cache-mysql"

[info]
port = ":8080"
service = "alpha"